StoreManagement/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("storeapp.urls")),
    path('polls/', include("polls.urls")),
]

polls/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.get_question, name='get-question'),
    path('validate/question/', views.validate_question, name='validate-question'),
    path('<int:question_id>/add-choice/', views.add_choice, name='add-choice'),
    path('<int:question_id>/votes/', views.votes, name='add-vote'),
]

polls/models.py
from django.db import models

# Create your models here.


class Question(models.Model):
    question_text = models.CharField(max_length=50, unique=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

    class Meta:
        unique_together = ("question", "choice_text")

polls/forms.py
from .models import Question, Choice
from django.forms import ModelForm


class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = ("question_text",)


class ChoiceForm(ModelForm):
    class Meta:
        model = Choice
        fields = ("choice_text", "votes")

polls/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect

from .models import Question, Choice
from .forms import QuestionForm

import json
from django.core import serializers

# Create your views here.


def index(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('index'))

    form = QuestionForm()
    question_list = Question.objects.all()
    print(question_list)
    return render(request, 'polls/index.html', {"question_list": question_list, "form": form})


def validate_question(request):
    question_text = request.GET.get('question_text', None)
    data = {
        'is_taken': Question.objects.filter(question_text__iexact=question_text).exists()
    }
    if data['is_taken']:
        data['error_message'] = 'Question already exists in the database'
    return JsonResponse(data)


def get_question(request, question_id):
    question = get_object_or_404(Question, id=question_id)
    return render(request, 'polls/get-question.html', {"question": question})


def add_choice(request, question_id):

    question = get_object_or_404(Question, id=question_id)
    try:
        new_choice = question.choice_set.create(
            choice_text=request.POST['choice_text'],
        )
        print(new_choice.id)
        obj = Choice.objects.get(id=new_choice.id)
        dct = {
            'id': obj.id,
            'choice_text': obj.choice_text,
            'votes': obj.votes,
        }
        json_object = json.dumps(dct, indent=4)
        print(obj)

        return JsonResponse(dct)
    except:
        # dct = {
        #         #     "msg": 'error in adding the choice check whether the choice is present for the current question'
        #         # }
        json_object = json.dumps('error in adding the choice check whether the choice is present for the current '
                                 'question')

        return JsonResponse(json_object)


def votes(request, question_id):

    question = get_object_or_404(Question, id=question_id)
    try:
        selected_choice = question.choice_set.get(id=request.POST['radioValue'])
        selected_choice.votes += 1
        selected_choice.save()
        dct = {
            'id': selected_choice.id,
            'choice_text': selected_choice.choice_text,
            'votes': selected_choice.votes,
        }
        json_object = json.dumps(dct, indent=4)
        print(selected_choice)

        return JsonResponse(dct)
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return HttpResponse({'error': "invalid "})

polls/templates/polls/get-question.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js">
    </script>
<body>
    <div>
        {{question.id}}) {{question.question_text}}<br>
        <div id="choice_div">
            <ul>
                <h2>List of choices for above question</h2>
                {% for choice in question.choice_set.all %}
                <li>
                    <input type="radio" name="choice" id="choice-{{ choice.id }}" value="{{ choice.id }}">
                    {{choice.choice_text}}
                    <input type="number" value="{{choice.votes}}" readonly style="text-align:center;" id="vote-{{choice.id}}" >
                </li>
                <br>
            {% endfor %}
            </ul>
            <button id="id_vote_add" data-vote-url="{% url 'add-vote' question.id %}">vote</button>

        </div>
    </div>
    <div>
        <div>
            <h1>Add new choices</h1>
        </div>
        <form action="" method="post" id="choice_form" data-choice-create-url="{% url 'add-choice' question.id %}">
            {% csrf_token %}
            Choice-Text-->><input type="text" name="choice_text" id="id_choice_text">
            votes-->><input type="text" name="votes" id="id_votes" readonly value="0">
            <input type="submit" value="create-choice" id="create_choice_button">
        </form>
    </div>
<script>
    $(document).ready(function(){
        alert('question and choices');
        console.log('hello');
        $(document).on('submit','#choice_form', function(e){
            e.preventDefault();
            var form = $(this).closest("form");
            var choice_div = $(this).closest("#choice_div");
            var result = {
                choice_text: $('#id_choice_text').val(),
                votes: $('#id_votes').val(),
                csrfmiddlewaretoken: $("input[name=csrfmiddlewaretoken]").val()
            };
            $.ajax({
                type:'POST',
                url:form.attr("data-choice-create-url"),
                data: result,

                success: function(responseTxt){
                    var element1 = '<input type="radio" name="choice" id="choice-'+responseTxt+'" value='+responseTxt.id+'>'
                    var element2 = responseTxt.choice_text+ '<input type="number" readonly style="text-align:center;" id="vote"  value='+ responseTxt.votes + '>'
                    element = '<li>'+element1+element2+'</li><br>'
                    $("ul").append(element);
                    $( '#choice_form' ).each(function(){
                        this.reset();
                        });
                    },
                error: function(error){
                    alert("error in adding the choice check whether the choice is present for the current question");
                    },
            });


        });

        $("#id_vote_add").click(function(){
            var radioValue = $("input[name='choice']:checked").val();
            var button = $(this).closest("button");
            var url=button.attr("data-vote-url");
            var dummy ="#vote-"+radioValue;
            var voteChoice=$(dummy).val();
            var result = {
                radioValue : $("input[name='choice']:checked").val(),
                csrfmiddlewaretoken: $("input[name=csrfmiddlewaretoken]").val(),
            };
            $.ajax({
                type:"POST",
                url:url,
                data:result,
                success: function(responseTxt){
                    $(dummy).val(responseTxt.votes)
                },
                error: function(){
                    alert('failed')
                }
            });
        });

    });
</script>
</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home Page</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js">
    </script>

</head>
<body>
<h1>Welcome to the HomePage</h1>
<div>
    <div id="question-form">
        <form method="post" data-validate-username-url="{% url 'validate-question' %}">
            {% csrf_token %}
        {% for field in form %}
        {{ field.label }}->>{{ field }}
        {% endfor %}
        <input type="submit" value="create a new question">
        </form>
    </div>
    <p id="p1"></p>
    <div id="questions">
        <h2>Question list</h2>
        {% for question in question_list %}
        <li><a href="{% url 'get-question' question.id %}">{{ question.question_text }}</a></li><br>
        {% endfor %}
    </div>
</div>

<script >
    $(document).ready(function(){
        alert('welcome')
        console.log('hello');
        $("#id_question_text").change(function(){
            console.log('step-1');
            var form = $(this).closest("form");
            console.log('step-2');
            $.ajax({
                url: form.attr("data-validate-username-url"),
                data: form.serialize(),
                dataType: 'json',
                success: function(data){
                    if (data.is_taken) {
                        alert(data.error_message);
                        $("p").show()
                        document.getElementById("p1").innerHTML = data.error_message ;
                        $("p").hide(1000)
                        form[0].reset();
                    }
                }

            });

        });
    });
    </script>
</body>
</html>